## END POINTS FOR ITEMS RESOURCE

### gets all items
GET http://localhost:3000/api/items

### get one item by id
GET http://localhost:3000/api/items/3

### posts new item
POST http://localhost:3000/api/items
Content-Type: application/json

{
  "name": "New item"
}

### updates item
PUT http://localhost:3000/api/items/1
Content-Type: application/json

{
  "name": "New name"
}

### deletes item
DELETE http://localhost:3000/api/items/1
content-type: application/json



## END POINTS FOR USERS RESOURCE

### Get all users
GET http://localhost:3000/api/users
Content-Type: application/json

### Get user by ID
GET http://localhost:3000/api/users/1
Content-Type: application/json

### Add new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "Newname",
  "password": "Password",
  "email": "newemail@email.com"
}


### user login
GET http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "Newname",
  "password": "Password"
}





## RANDOM PRACTICE


### GET testi
GET http://localhost:3000

### toinen GET testi
GET http://localhost:3000/moro

### POST testi
POST http://localhost:3000/api/moro
Content-Type: application/json

{
  "sender": "Sender",
  "message": "Hello World!"
}

### KERTAUS testi
POST http://localhost:3000/api/square/10
Content-Type: application/json

{
  "Application": "Square of the number"
}
