# GET testi
GET http://localhost:3000

### toinen GET testi
GET http://localhost:3000/moro

### POST testi
POST http://localhost:3000/api/moro
content-type: application/json

{
  "sender": "Sender",
  "message": "Hello World!"
}

### KERTAUS testi
POST http://localhost:3000/api/square/10
content-type: application/json

{
  "Application": "Square of the number"
}
